---
title: "Representation of GAs"
output: rmarkdown::html_vignette
toc: true
vignette: >
  %\VignetteIndexEntry{Representation of GAs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "figures/theory-",
    out.width = "100%"
)
```

```{r echo=FALSE}
library(DiagrammeR)

grViz("
  digraph genetic_algorithm {
    rankdir=LR;
    
    A [label = 'Initialize Population'];
    B [label = 'Evaluate Fitness'];
    C [label = 'Selection'];
    D [label = 'Termination Condition?'];
    E [label = 'End'];
    F [label = 'Crossover and Mutation'];
    G [label = 'Replace Population'];
    
    X1 [label = 'Individual 1: x = 1', shape = ellipse];
    X2 [label = 'Individual 2: x = 3', shape = ellipse];
    X3 [label = 'Individual 3: x = 0', shape = ellipse];
    
    Y1 [label = 'Selected Parents: x = 1, x = 3', shape = ellipse];
    
    Z1 [label = 'Offspring 1: x = 1', shape = ellipse];
    Z2 [label = 'Offspring 2: x = 3', shape = ellipse];
    
    A -> B;
    B -> C;
    C -> D;
    D -> E [label = 'Yes'];
    D -> F [label = 'No'];
    F -> G;
    G -> B;
    
    # Examples
    B -> X1 [label = 'Example:'];
    B -> X2;
    B -> X3;
    
    C -> Y1 [label = 'Example:'];
    
    F -> Z1 [label = 'Example:'];
    F -> Z2;
  }
")

```

